[package]
name = "notty-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
notty-core = { path = "../notty-core" }
notty-io = { path = "../notty-io" }
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_Graphics_Dwm", "Win32_System_LibraryLoader", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_Registry"] }

[dev-dependencies]
tempfile.workspace = true
