//! notty-ui: ventana Win32, render Direct2D/DirectWrite y lógica de edición en pantalla.

mod anim;
pub mod chrome_text;
pub mod clipboard;
pub mod context_menu;
mod doc_io;
pub mod editor;
mod keyboard_widget;
mod hex;
pub mod layout;
mod keymap;
pub mod ligature;
pub mod menu;
pub mod native_dialog;
mod path_prompt;
mod prompt;
mod raw_doc;
pub mod render;
mod search_prompt;
pub mod splits;
pub mod settings_model;
pub mod settings_window;
pub mod step_rail;
pub mod tab_anim;
mod theme;
pub mod tour;
pub mod update_panel;
mod viewport;
mod vim;
mod vim_cmd;
pub mod welcome_window;
pub mod window;
pub mod workspace;

pub use anim::{Anim, ease_out_cubic};
pub use chrome_text::*;
pub use doc_io::{OpenedDoc, open_as_document, save_document};
pub use editor::EditorState;
pub use hex::{hex_char, hex_row, hex_rows};
pub use keymap::{EditorAction, Modifiers, action_for_vk};
pub use path_prompt::{OVERWRITE_QUESTION, OverwriteChoice, PathPromptState, Purpose};
pub use prompt::Prompt;
pub use raw_doc::{RawDoc, open_raw_doc};
pub use render::{AboutContent, Hit, Renderer, UpdatePanelContent, ViewState};
pub use search_prompt::SearchState;
pub use theme::{Palette, Rgba, is_dark, palette};
pub use update_panel::{DownloadPhase, UpdateState};
pub use viewport::Viewport;
pub use vim::{VimMode, VimOutcome, VimState};
pub use vim_cmd::{VimCmd, parse_vim_cmd};
pub use workspace::Workspace;
