//! Traducción de la interfaz (Ajustes → Idioma): español siempre disponible sin
//! tocar nada (es el texto que ya escribe cada función de dibujo), inglés como
//! tabla de búsqueda sobre ese mismo texto. `tr(lang, "Nuevo")` devuelve "New" si
//! `lang` es `En` y "Nuevo" está en la tabla; si no está (todavía no traducido, o
//! `lang` es `Es`), devuelve el español tal cual — nunca un hueco en blanco.
//!
//! No es la única forma de hacerlo (un `struct` con un campo por texto lo
//! comprobaría en tiempo de compilación), pero sobre ~800 cadenas ya escritas en
//! docenas de funciones de dibujo, envolver cada una en `tr(lang, "...")` es el
//! cambio más pequeño que no obliga a rehacer cómo están escritas.

use notty_config::Lang;

/// (español, inglés). Buscar es O(n) sobre esta tabla, pero se llama pintando la
/// interfaz (decenas de veces por fotograma como mucho, nunca en un bucle sobre el
/// texto del documento), así que no hace falta nada más rápido.
const TABLE: &[(&str, &str)] = &[
    // --- menu.rs: barra de menús ---
    ("Archivo", "File"),
    ("Editar", "Edit"),
    ("Buscar", "Search"),
    ("Ver", "View"),
    ("Ayuda", "Help"),
    ("Nuevo", "New"),
    ("Nuevo temporal", "New scratch file"),
    ("Abrir", "Open"),
    ("Guardar", "Save"),
    ("Guardar como", "Save As"),
    ("Ajustes", "Settings"),
    ("Cerrar pestaña", "Close Tab"),
    ("Deshacer", "Undo"),
    ("Rehacer", "Redo"),
    ("Reemplazar", "Replace"),
    ("Siguiente", "Next"),
    ("Anterior", "Previous"),
    ("Números de línea", "Line Numbers"),
    ("Barra de atajos", "Hints Bar"),
    ("Modo vim", "Vim Mode"),
    ("Ver como raw", "View as Raw"),
    ("Previsualización de Markdown", "Markdown Preview"),
    ("Ver Markdown como previsualización", "View Markdown as Preview"),
    ("Atajos de teclado", "Keyboard Shortcuts"),
    ("Acerca de notty", "About notty"),
    // --- settings_model.rs: Page::name ---
    ("Apariencia", "Appearance"),
    ("Fuentes", "Fonts"),
    ("Ligaduras", "Ligatures"),
    ("Sintaxis", "Syntax"),
    ("Idioma", "Language"),
    ("Ventana", "Window"),
    ("Teclado", "Keyboard"),
    ("Archivos", "Files"),
    ("Atajo global", "Global Shortcut"),
    ("Actualizaciones", "Updates"),
    ("Acerca de", "About"),
    // "Ayuda" ya está arriba (menú Ayuda / página Ayuda comparten texto).
    // --- settings_pages.rs: cabeceras y grupos de cada página ---
    ("Los cambios se ven al instante", "Changes take effect instantly"),
    ("Personalizado · los cambios se ven al instante", "Custom · changes take effect instantly"),
    ("Preset", "Preset"),
    ("Tema", "Theme"),
    ("Color de acento", "Accent color"),
    ("Azul", "Blue"),
    ("Verde", "Green"),
    ("Turquesa", "Turquoise"),
    ("Morado", "Purple"),
    ("Rosa", "Pink"),
    ("Rojo", "Red"),
    ("Naranja", "Orange"),
    ("Amarillo", "Yellow"),
    ("Sistema", "System"),
    ("Claro", "Light"),
    ("Oscuro", "Dark"),
    ("Moderna", "Modern"),
    ("Clásica", "Classic"),
    ("Zen", "Zen"),
    ("Fuente", "Font"),
    ("Desactivadas", "Off"),
    ("Resaltado de sintaxis", "Syntax highlighting"),
    ("Así queda la ventana principal", "This is how the main window looks"),
    ("Varios archivos", "Multiple files"),
    ("Ajustar texto a la ventana", "Wrap text to fit the window"),
    ("Las líneas largas pasan a la siguiente línea en vez de salirse por el borde.", "Long lines wrap to the next line instead of running off the edge."),
    ("Restablecer tamaño de ventana", "Reset window size"),
    ("Vuelve al tamaño de siempre la próxima vez que abras notty.", "Goes back to the default size the next time you open notty."),
    ("Guardar por defecto en", "Save by default to"),
    ("Carpeta de usuario", "User folder"),
    ("Documentos", "Documents"),
    ("Descargas", "Downloads"),
    ("Abrir .md en", "Open .md as"),
    ("Texto", "Text"),
    ("Previsualización", "Preview"),
    ("Solo lectura", "Read-only"),
    ("En línea", "Inline"),
    ("Moverse", "Move"),
    ("Salir de previsualización", "Exit preview"),
    ("Ver como texto", "View as text"),
    ("Una pestaña por archivo, visibles arriba.", "One tab per file, visible at the top."),
    ("Estilo vim: sin pestañas, cambias con Ctrl+Tab o :b.", "Vim style: no tabs, switch with Ctrl+Tab or :b."),
    ("Pestañas que se dividen en hasta 4 paneles, como kitty. Ctrl+Shift+Enter divide, Ctrl+Shift+R acomoda.", "Tabs that split into up to 4 panes, like kitty. Ctrl+Shift+Enter splits, Ctrl+Shift+R tiles."),
    ("Editar config.toml", "Edit config.toml"),
    ("Pestañas", "Tabs"),
    ("Buffers", "Buffers"),
    ("Paneles", "Panes"),
    ("Posición de las pestañas", "Tab position"),
    ("Iconos en las pestañas", "Tab icons"),
    ("Un icono de archivo genérico delante del nombre.", "A generic file icon before the name."),
    ("En el título", "In the title bar"),
    ("Bajo el menú", "Below the menu"),
    ("Si hay más de 1", "If there's more than 1"),
    ("Ocultas", "Hidden"),
    ("Barra de menús", "Menu bar"),
    ("Visible", "Visible"),
    ("Con Alt", "With Alt"),
    ("Estilo nano. Cambia según lo que estés haciendo.", "Nano-style. Changes with what you're doing."),
    ("Barra de estado", "Status bar"),
    ("Si la ocultas, reaparece para rutas, búsquedas y avisos.", "If you hide it, it reappears for paths, searches and notices."),
    ("Línea de comandos fusionada", "Merged command line"),
    ("Una sola línea abajo para estado y comandos, como en Zen.", "A single line at the bottom for status and commands, like Zen."),
    ("Así se abre y guarda", "This is how files open and save"),
    ("Archivos temporales", "Scratch files"),
    ("Borrador", "Draft"),
    ("Se guarda solo; se borra al cerrar si no le das ruta.", "Saves itself; deleted on close if you never give it a path."),
    ("Volátil", "Volatile"),
    ("Nunca toca el disco. Al cerrar, desaparece.", "Never touches disk. Gone when you close it."),
    ("Diálogo de Windows", "Windows dialog"),
    ("Selector nativo de Windows", "Native Windows picker"),
    ("Abrir y Guardar como usan el diálogo de Windows en vez de la línea de ruta.", "Open and Save As use the Windows dialog instead of the path line."),
    ("Iconos en las sugerencias", "Icons in suggestions"),
    ("Carpeta o archivo delante de cada sugerencia al escribir una ruta.", "Folder or file before each suggestion while typing a path."),
    ("Autoguardado", "Autosave"),
    ("Guarda sola tras dejar de escribir. Solo si el archivo ya tiene ruta.", "Saves itself after you stop typing. Only if the file already has a path."),
    ("Abrir archivos en la ventana ya abierta", "Open files in the already-open window"),
    ("Si lo apagas, cada archivo que abras desde el Explorador sale en una ventana nueva.", "If you turn this off, every file you open from Explorer opens in a new window."),
    ("Reabrir archivos anteriores", "Reopen previous files"),
    ("Al abrir notty sin darle ningún archivo, vuelve a abrir los que quedaron abiertos la última vez.", "Opening notty with no file reopens whatever was still open last time."),
    ("Al cerrar con cambios sin guardar", "When closing with unsaved changes"),
    ("Preguntar", "Ask"),
    ("Recuperar al abrir", "Recover on open"),
    ("Auto", "Auto"),
    ("Español", "Spanish"),
    ("English", "English"),
    ("De Windows", "From Windows"),
    ("Palabra clave", "Keyword"),
    ("Cadena", "String"),
    ("Número", "Number"),
    ("Tipo", "Type"),
    ("Función", "Function"),
    ("Comentario", "Comment"),
    ("El idioma de la interfaz. \"Auto\" sigue el de Windows.", "The interface language. \"Auto\" follows Windows' own language."),
    // --- settings_pages.rs: Teclado ---
    ("Atajos · haz clic en uno para cambiarlo", "Shortcuts · click one to change it"),
    ("Para moverte · fijos", "To move around · fixed"),
    ("Atajos globales · funcionan aunque notty no tenga el foco", "Global shortcuts · work even without notty focused"),
    ("Pestaña siguiente / anterior", "Next / previous tab"),
    ("Ir a la pestaña 1…9 (9 = la última)", "Go to tab 1…9 (9 = the last one)"),
    ("Ir al panel 1…9 (modo Paneles)", "Go to pane 1…9 (Panes mode)"),
    ("En Acomodar: ancho · panel · igualar · salir", "In Arrange: width · pane · equalize · exit"),
    ("Nuevo permanente", "New permanent file"),
    ("Todos los atajos", "All shortcuts"),
    ("Cada acción es un comando con nombre; también en config.toml, sección [keys].", "Every action is a named command; also in config.toml, section [keys]."),
    ("Abrir [keys]", "Open [keys]"),
    ("Modo vim siempre", "Always vim mode"),
    ("Cada ventana arranca en modo vim. ", "Every window starts in vim mode. "),
    (" para insertar, ", " to insert, "),
    (" para salir.", " to exit."),
    ("i para insertar, Esc para salir.", "i to insert, Esc to exit."),
    ("sin atajo", "no shortcut"),
    ("Abrir Ajustes", "Open Settings"),
    ("Nueva pestaña", "New tab"),
    ("Nueva pestaña temporal", "New scratch tab"),
    ("Pestaña siguiente", "Next tab"),
    ("Pestaña anterior", "Previous tab"),
    ("Alternar vim en esta ventana", "Toggle vim in this window"),
    ("Aumentar tamaño del texto", "Increase text size"),
    ("Reducir tamaño del texto", "Decrease text size"),
    ("Restablecer tamaño del texto", "Reset text size"),
    ("Dividir panel", "Split pane"),
    ("Cerrar panel", "Close pane"),
    ("Panel de la izquierda", "Pane to the left"),
    ("Panel de la derecha", "Pane to the right"),
    ("Mover el panel a la izquierda", "Move pane left"),
    ("Mover el panel a la derecha", "Move pane right"),
    ("Acomodar paneles (ajustar anchos)", "Arrange panes (adjust widths)"),
    ("Mover la pestaña a la izquierda", "Move tab left"),
    ("Mover la pestaña a la derecha", "Move tab right"),
    // --- settings_pages.rs: Atajo global ---
    ("Cómo se escucha el atajo", "How the shortcut is heard"),
    ("Segundo plano", "Background"),
    ("~1 MB de RAM · cualquier combinación · instantáneo", "~1 MB of RAM · any combination · instant"),
    ("Acceso directo", "Shortcut file"),
    ("Nada residente · solo Ctrl+Alt+letra", "Nothing resident · only Ctrl+Alt+letter"),
    ("Iniciar con Windows", "Start with Windows"),
    ("sin título", "untitled"),
    // --- settings_pages.rs: Actualizaciones ---
    ("notty está al día", "notty is up to date"),
    ("Tienes la última versión publicada.", "You have the latest published version."),
    ("Sin comprobar en esta sesión", "Not checked this session"),
    ("Busca cuando quieras: se consultan las releases de GitHub.", "Check whenever you like: this queries GitHub Releases."),
    ("Buscando…", "Checking…"),
    ("Consultando las releases de GitHub.", "Querying GitHub Releases."),
    ("Hay una versión nueva", "There's a new version"),
    ("Descargando", "Downloading"),
    ("Se verifica la firma al terminar.", "The signature is verified once it's done."),
    ("No se pudo actualizar", "Couldn't update"),
    ("No se pudo comprobar", "Couldn't check"),
    ("Descargar e instalar", "Download and install"),
    ("Buscar actualizaciones", "Check for updates"),
    ("Novedades de", "What's new in"),
    ("Esta versión no trae notas.", "This version has no release notes."),
    ("Ver todas las notas en GitHub", "See all notes on GitHub"),
    ("Buscar al abrir notty", "Check when notty opens"),
    ("Una vez al día contra GitHub Releases. Nunca se activa solo.", "Once a day against GitHub Releases. Never turns itself on."),
    ("Cada instalador se comprueba con Ed25519 antes de ejecutarse.", "Every installer is verified with Ed25519 before it runs."),
    ("Firma verificada", "Signature verified"),
    ("Siempre", "Always"),
    ("Versión instalada ", "Installed version "),
    ("Última comprobación", "Last checked"),
    // --- settings_pages.rs: Acerca de ---
    ("El Bloc de notas, pero rápido y con teclado.", "Notepad, but fast and keyboard-driven."),
    ("Buscando actualizaciones…", "Checking for updates…"),
    ("Al día", "Up to date"),
    ("Información", "Information"),
    ("Versión", "Version"),
    ("Plataforma", "Platform"),
    ("Configuración", "Config"),
    ("Instalado en", "Installed in"),
    ("Código fuente", "Source code"),
    ("Informar de un problema", "Report a problem"),
    ("Abre una incidencia en GitHub", "Opens an issue on GitHub"),
    ("Novedades", "What's new"),
    ("Historial de cambios de cada versión", "Changelog of every version"),
    ("Carpeta de configuración", "Config folder"),
    ("Hecho con Rust, Direct2D, DirectWrite y tree-sitter.", "Made with Rust, Direct2D, DirectWrite and tree-sitter."),
    // --- settings_pages.rs: Ayuda ---
    ("El recorrido guiado sobre la ventana principal, paso a paso.", "The guided tour of the main window, step by step."),
    ("Repetir tutorial", "Repeat tutorial"),
    ("Lo básico", "The basics"),
    ("Abrir archivo", "Open file"),
    ("Tamaño del texto", "Text size"),
    // --- settings_pages.rs: Fuentes ---
    ("Tamaño", "Size"),
    ("Texto de muestra", "Sample text"),
    ("Buscar fuente", "Search font"),
    ("Buscando fuentes…", "Looking for fonts…"),
    ("Ninguna fuente monoespaciada coincide con la búsqueda.", "No monospace font matches the search."),
    // --- settings_pages.rs: Ligaduras ---
    ("Activadas", "On"),
    ("Tal como lo escribes", "As you type it"),
    ("Tal como lo ves", "As you see it"),
    ("Añadir ligadura", "Add ligature"),
    ("Se guarda en config.toml", "Saved to config.toml"),
    ("De serie", "Built-in"),
    ("Propia", "Custom"),
    // --- settings_pages.rs: Sintaxis ---
    ("Activado", "On"),
    ("Desactivar todos", "Turn all off"),
    ("Activar todos", "Turn all on"),
    ("Desactivado", "Off"),
    // --- render.rs: diálogos de cierre / conflicto ---
    ("Cancelar", "Cancel"),
    ("No guardar", "Don't save"),
    ("Escribe SI o NO y pulsa Enter · Esc cancela", "Type YES or NO and press Enter · Esc cancels"),
    // --- settings_model.rs: relative_time ---
    ("nunca", "never"),
    ("ahora mismo", "just now"),
    // --- render.rs: línea de ruta (Abrir/Guardar) ---
    ("ruta del archivo", "file path"),
    ("ruta donde guardar", "path to save to"),
    ("Sobrescribir", "Overwrite"),
    ("Ya existe:", "Already exists:"),
    ("Tab ↹", "Tab ↹"),
    ("nuevo", "new"),
    ("existe", "exists"),
    ("carpeta", "folder"),
    ("carpeta nueva", "new folder"),
    ("no válido", "invalid"),
    // --- update_panel.rs ---
    ("ya tienes la última versión", "you already have the latest version"),
    ("La descarga no es auténtica", "The download isn't authentic"),
    ("no se pudo crear el directorio temporal", "couldn't create the temp directory"),
    ("no se pudo leer lo descargado", "couldn't read what was downloaded"),
    ("Acomodar paneles", "Arrange panes"),
    ("←/→ ancho · Shift más rápido · Tab panel · = igualar · Esc salir", "←/→ width · Shift faster · Tab pane · = equalize · Esc exit"),
    ("Ruta copiada al portapapeles", "Path copied to clipboard"),
    ("Editor de texto nativo para Windows", "Native text editor for Windows"),
    ("escritura", "editing"),
    ("solo lectura", "read-only"),
    ("Guardar como…", "Save as…"),
    ("buscar", "find"),
    ("por", "with"),
    // --- context_menu.rs ---
    ("Cerrar", "Close"),
    ("Copiar", "Copy"),
    ("Cerrar las demás", "Close others"),
    ("Cerrar las de la derecha", "Close tabs to the right"),
    ("Copiar ruta", "Copy path"),
    ("Abrir carpeta contenedora", "Open containing folder"),
    ("Buscar la selección", "Find selection"),
    ("Reemplazar la selección", "Replace selection"),
    ("Cortar", "Cut"),
    ("Pegar", "Paste"),
    ("Eliminar", "Delete"),
    ("Seleccionar todo", "Select all"),
    ("Buscar siguiente", "Find next"),
    ("Buscar anterior", "Find previous"),
    // --- tour.rs / welcome_window.rs: bienvenida y recorrido ---
    ("Atrás", "Back"),
    ("Empezar", "Get started"),
    ("Saltar", "Skip"),
    ("Terminar", "Finish"),
    // --- tour.rs ---
    ("Ctrl+N abre una nueva y Ctrl+W la cierra. Arrastra para reordenar.", "Ctrl+N opens a new one and Ctrl+W closes it. Drag to reorder."),
    ("Tema, estilo, fuente y modo de teclado, en cualquier momento.", "Theme, style, font and keyboard mode, any time."),
    ("Abrir rápido", "Quick open"),
    ("Abre una ruta con autocompletado, sin diálogo.", "Open a path with autocomplete, no dialog."),
    ("Línea, codificación y fin de línea. Haz clic en cualquiera para cambiarlo.", "Line, encoding and line ending. Click any of them to change it."),
    ("Para curiosos", "For the curious"),
    ("Activa vim y muestra los bytes en crudo.", "Turns on vim and shows the raw bytes."),
    ("Hecho", "Done"),
    ("Siguiente →", "Next →"),
    ("← Atrás", "← Back"),
    ("¡Eso es!", "That's it!"),
    ("Pulsa", "Press"),
    // --- welcome_window.rs ---
    ("Bienvenido a notty", "Welcome to notty"),
    ("Estilo", "Style"),
    ("Privacidad", "Privacy"),
    ("Listo", "Done"),
    ("Pestañas en la barra de título, sin menús", "Tabs in the title bar, no menus"),
    ("Menú Archivo · Editar · Ver, como siempre", "File · Edit · View menu, as usual"),
    ("Usar el de Windows", "Use Windows setting"),
    ("Normal", "Normal"),
    ("Como cualquier editor de Windows", "Like any Windows editor"),
    ("Vim", "Vim"),
    ("Modos Normal / Insertar / Visual", "Normal / Insert / Visual modes"),
    ("Avisarme de nuevas versiones", "Notify me of new versions"),
    ("No, lo miraré yo", "No, I'll check myself"),
    ("Ajustes → Acerca de → Buscar ahora", "Settings → About → Check now"),
    ("Cuatro preguntas rápidas y listo. Todo se aplica al momento en la ventana de detrás, y puedes cambiarlo luego en Ajustes.", "Four quick questions and you're set. Everything applies live to the window behind, and you can change it later in Settings."),
    ("¿Cómo quieres la ventana?", "How do you want the window?"),
    ("Claro, oscuro o el que use Windows.", "Light, dark, or whatever Windows uses."),
    ("Si no sabes qué es vim, deja \"Normal\".", "If you don't know what vim is, leave \"Normal\"."),
    ("notty no se conecta a nada sin tu permiso. Si lo activas, solo consulta una vez al día si hay versión nueva en GitHub: sin datos, sin identificadores.", "notty doesn't connect to anything without your permission. If you turn it on, it only checks once a day for a new version on GitHub: no data, no identifiers."),
    ("Todo listo", "All set"),
    ("¿Te enseño en 20 segundos dónde está cada cosa?", "Want a 20-second tour of where everything is?"),
    ("Con barra de menús", "With a menu bar"),
    ("Solo el texto", "Just the text"),
    ("Archivo  Editar  Ver", "File  Edit  View"),
    ("Enséñame dónde está todo →", "Show me where everything is →"),
    ("Puedes repetirlo desde Ajustes → Ayuda.", "You can repeat this from Settings → Help."),
    // --- window.rs: avisos y título de ventana ---
    ("No se pudo guardar para recuperar", "Couldn't save for recovery"),
    ("No se pudo guardar", "Couldn't save"),
    ("Como mucho", "At most"),
    ("paneles por pestaña", "panes per tab"),
    ("No se pudo autoguardar", "Couldn't autosave"),
    ("Autoguardado en pausa hasta que guardes a mano", "Autosave paused until you save by hand"),
    ("No se pudo leer el archivo", "Couldn't read the file"),
    ("Para acomodar hacen falta dos paneles (Ctrl+Shift+Enter divide)", "Arranging needs two panes (Ctrl+Shift+Enter splits)"),
    ("Guarda antes de salir de raw", "Save before leaving raw"),
    ("Guarda antes de ver como raw", "Save before viewing as raw"),
    ("config.toml roto", "config.toml broken"),
    ("no se pudo guardar la sesión", "couldn't save the session"),
    ("Descargando...", "Downloading..."),
    // --- editor.rs: errores de guardado ---
    ("sin ruta", "no path"),
    ("tiene bytes ilegibles; guárdalo con otro nombre", "has unreadable bytes; save it under another name"),
    // --- notty-setup/src/ui.rs: errores de MSI ---
    ("Windows Installer encontró un error grave durante la instalación.", "Windows Installer ran into a serious error during installation."),
    ("No se pudo abrir el paquete de instalación.", "Couldn't open the installation package."),
    ("El paquete de instalación no es válido o está dañado.", "The installation package is invalid or damaged."),
    ("Una directiva del sistema impide esta instalación.", "A system policy blocks this installation."),
    ("Este paquete no es compatible con este equipo.", "This package isn't compatible with this computer."),
    ("Ya hay otra versión de notty instalada. Desinstálala desde Aplicaciones instaladas.", "notty is already installed. Uninstall it from Installed Apps first."),
    ("La instalación no se ha completado.", "The installation didn't complete."),
    // --- notty-setup/src/ui.rs: carril de pasos ---
    ("Bienvenida", "Welcome"),
    ("Instalar", "Install"),
    // --- notty-setup/src/ui.rs: opciones ---
    ("Sustituir el Bloc de notas", "Replace Notepad"),
    ("\"notepad\" abre notty · el original queda como notepad_legacy", "\"notepad\" opens notty · the original stays as notepad_legacy"),
    ("\"Abrir con notty\" en el menú contextual", "\"Open with notty\" in the context menu"),
    ("Usar notty desde la terminal", "Use notty from the terminal"),
    ("Añade notty al PATH", "Adds notty to PATH"),
    ("Texto plano", "Plain text"),
    ("Código y datos", "Code and data"),
    ("Menú Inicio", "Start Menu"),
    ("Escritorio", "Desktop"),
    ("Integración con Windows", "Windows integration"),
    ("Bloc de notas, menú contextual, terminal", "Notepad, context menu, terminal"),
    ("Tipos de archivo", "File types"),
    ("Qué archivos ofrece abrir notty", "Which files notty offers to open"),
    ("Accesos directos", "Shortcuts"),
    ("Avanzado", "Advanced"),
    ("Carpeta de instalación", "Installation folder"),
    ("Escribir \"notepad\" en cualquier sitio abrirá notty. El Bloc de notas original sigue disponible.", "Typing \"notepad\" anywhere will open notty. The original Notepad stays available."),
    ("Clic derecho sobre cualquier archivo → Abrir con notty. En Windows 11, dentro de \"Mostrar más opciones\".", "Right-click any file → Open with notty. On Windows 11, inside \"Show more options\"."),
    ("Escribe notty seguido de un archivo desde cmd o PowerShell.", "Type notty followed by a file from cmd or PowerShell."),
    ("notty aparecerá en \"Abrir con\" para estos tipos. Al terminar podrás elegirlo como predeterminado.", "notty will appear in \"Open with\" for these types. You can set it as default once it's done."),
    ("notty aparece en la lista de aplicaciones del menú Inicio.", "notty appears in the Start menu's app list."),
    ("Dónde se copian los archivos. Hace falta una carpeta con permisos de administrador.", "Where the files are copied. It needs a folder with administrator permissions."),
    // --- notty-setup/src/ui.rs: bienvenida ---
    ("Un bloc de notas ligero para Windows. Se instalará para todos los usuarios de este equipo.", "A lightweight notepad for Windows. It will be installed for every user on this computer."),
    ("CARPETA", "FOLDER"),
    ("Cambiar…", "Change…"),
    ("2,3 MB · Windows 10 1809 o posterior", "2.3 MB · Windows 10 1809 or later"),
    ("Comprobando la última versión…", "Checking for the latest version…"),
    ("No se pudo comprobar si hay una versión más nueva.", "Couldn't check for a newer version."),
    // --- notty-setup/src/ui.rs: opciones (encabezado) ---
    ("Opciones", "Options"),
    ("Todo se puede cambiar después desde Ajustes.", "Everything can be changed later from Settings."),
    ("VISTA PREVIA", "PREVIEW"),
    // --- notty-setup/src/ui.rs: escenas de la vista previa ---
    (" se abre ", " opens "),
    (" Bloc de notas original", " Original Notepad"),
    (" abierto en una pestaña nueva", " opened in a new tab"),
    ("Abrir con notty", "Open with notty"),
    ("Propiedades", "Properties"),
    ("Anclado", "Pinned"),
    // --- notty-setup/src/ui.rs: instalando ---
    ("Instalando…", "Installing…"),
    ("No tardará más de unos segundos.", "It won't take more than a few seconds."),
    ("Otra instalación en curso", "Another installation is in progress"),
    ("Espera a que termine la otra instalación y pulsa Reintentar.", "Wait for the other installation to finish, then press Retry."),
    ("No se pudo instalar notty", "notty couldn't be installed"),
    ("Código", "Code"),
    ("Código de MSI", "MSI code"),
    ("Registro", "Log"),
    // --- notty-setup/src/ui.rs: listo ---
    ("notty está listo", "notty is ready"),
    ("Falta un paso: elegir notty como app predeterminada para .txt en Ajustes de Windows.", "One step left: set notty as the default app for .txt in Windows Settings."),
    // --- notty-setup/src/ui.rs: pie de página ---
    ("Volver a Opciones", "Back to Options"),
    ("Copiado ✓", "Copied ✓"),
    ("Copiar detalles", "Copy details"),
    ("Abrir el registro", "Open the log"),
    ("Reintentar", "Retry"),
    ("Abrir notty", "Open notty"),
    ("Abrir Aplicaciones predeterminadas", "Open Default Apps"),
    // --- notty-setup/src/msi_driver.rs: texto de progreso de MSI ---
    ("Preparando la instalación", "Preparing installation"),
    ("Quitando la versión anterior", "Removing the previous version"),
    ("Copiando archivos", "Copying files"),
    ("Escribiendo en el registro", "Writing to the registry"),
    ("Registrando asociaciones de archivo", "Registering file associations"),
    ("Creando accesos directos", "Creating shortcuts"),
    ("Actualizando el PATH", "Updating PATH"),
    ("Registrando notty en Windows", "Registering notty with Windows"),
    ("Terminando", "Finishing"),
    // --- notty-setup/src/main.rs ---
    ("Carpeta de instalación de notty", "notty installation folder"),
    ("Instalar notty", "Install notty"),
    ("Actualizar notty", "Update notty"),
    ("Actualización disponible", "Update available"),
    (" · firma verificada ✓", " · signature verified ✓"),
    ("· Barra de título más compacta\n· Sombras suaves en los desplegables\n· Cursor de bloque en vim Normal", "· More compact title bar\n· Soft shadows on dropdowns\n· Block cursor in vim Normal mode"),
    ("Tus pestañas y borradores se restaurarán al terminar.", "Your tabs and drafts will be restored when it's done."),
    ("Actualizar", "Update"),
    ("Más tarde", "Later"),
    ("Actualizando", "Updating"),
    ("Este notty-setup se compiló sin el paquete MSI dentro (falta installer\\notty.msi al compilar). Construye el MSI con tools/release.ps1 y vuelve a compilar notty-setup.", "This notty-setup was built without the MSI package inside (installer\\notty.msi was missing at build time). Build the MSI with tools/release.ps1 and rebuild notty-setup."),
    ("No se pudo extraer el paquete a la carpeta temporal", "Couldn't extract the package to the temp folder"),
];

/// Traduce `es` a `lang`. Si `lang` es `Es`, o no hay traducción en la tabla,
/// devuelve `es` sin tocar (por eso acepta cualquier `&str`, no solo `&'static`:
/// también hay que poder traducir texto generado en tiempo de dibujo, como "5 de 21
/// lenguajes activos", que se queda tal cual porque no está en la tabla).
pub fn tr<'a>(lang: Lang, es: &'a str) -> &'a str {
    if lang != Lang::En {
        return es;
    }
    TABLE.iter().find(|(s, _)| *s == es).map(|(_, e)| *e).unwrap_or(es)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spanish_is_always_the_literal_text() {
        assert_eq!(tr(Lang::Es, "Archivo"), "Archivo");
        assert_eq!(tr(Lang::Es, "algo sin traducir"), "algo sin traducir");
    }

    #[test]
    fn english_translates_known_strings() {
        assert_eq!(tr(Lang::En, "Archivo"), "File");
        assert_eq!(tr(Lang::En, "Guardar como"), "Save As");
    }

    #[test]
    fn english_falls_back_to_spanish_for_unknown_strings() {
        assert_eq!(tr(Lang::En, "algo sin traducir"), "algo sin traducir");
    }

    #[test]
    fn table_has_no_duplicate_spanish_keys() {
        let mut seen = std::collections::HashSet::new();
        for (es, _) in TABLE {
            assert!(seen.insert(*es), "clave repetida en la tabla: {es}");
        }
    }
}
